### ISSUE TITLE
Calculate UNIX/EPOCH Timestamp | Contiki OS

### ISSUE THREAD

**Issue by kaleemullah360** [contiki-os/contiki#1648]
is there a way to calculate `UNIX/EPOCH` `Timestamp` in `Contiki` Examples, so that it could be compared with outer world Timestamp. I've tried different ways. but nothing worked. like 

```
  clock_seconds();  // UpTime
  clock_time(); // ClockTime
```
please help me to compute `Timestamp`.
thank you.

**Comment by vsaw** [comment]
The problem is that most boards that contiki is running on don't have a battery powered Real Time Clock. Therefore the clocks usually reset whenever the CPU resets. This is why non of the clocks in contiki can be converted to Unix timestamps out of the box, they don't know the real world time. This leaves you with essentially two options

1. Run on a board with a Real Time Clock, read the RTC and convert to unix timestamps. This depends on your hardware which is why I can not be more specific on how to do it.
2. Find/Write an NTP client for contiki and obtain the timestamp from the network. This will work on any Contiki board but requires an NTP server in your network or a connection to the internet.
