### ISSUE TITLE
mqtt with launchpad cc2650

### ISSUE THREAD

**Issue by saulofr** [contiki-os/contiki#1700]
@g-oikonomou I can connect the  launchpad with a MQTT broker by 6lbr IP64 config? I try change the ip broker using RFC 6052 prefix but it dont work.

**Comment by xukai871105** [comment]
We have the same problem。When we use 6lbr and turn on the IP64 function, We find that UPD work well, But there is something wrong with TCP.Because of TCP error, We could not use MQTT client to connect a local borker or IBM Bluemix(IoT Waston Platform). We tried to fix the problem using CC2538dk and CC1310DK.

**Comment by g-oikonomou** [comment]
I've used CC2650 + MQTT + NAT64 + Bluemix in the past, zero problems. The only difference I can see to what you are describing is that I was not using IP64 for NAT64, I was using wrapsix on a Beaglebone Black.

From what is being described here, this doesn't appear to be a problem with the LP or CC2650 specifically, most likely not a problem with MQTT either.

If UDP works but TCP does not, then we'll need more information in order to figure out why.

**Comment by xukai871105** [comment]
We have tested CC1310DK + rpl_board_router + tunsilp6 + MQTT(or http-example) + NAT64(Jool).There is no problem in this situation. When we use 6lbr + slip-radio instead of rpl_board_router + tunslip6 a TCP error happens. CC1310dk can send TCP SYN at the right way but can not receive TCP SYN+ACK. HTTP server or MQTT broker tries to retransmit SYN+ACK but it has no effect. In this pcap file, CC1310dk IP address: 192.168.1.194.Http server IP address 192.168.1.104.
![wireshark result](https://cloud.githubusercontent.com/assets/3615443/15745978/2243184c-2907-11e6-9da8-c5d6d5f39975.png)
Please forgive my poor English.

**Comment by g-oikonomou** [comment]
@laurentderu Could this be a problem in 6lbr, Laurent?

**Comment by alignan** [comment]
Have you tried using the `::ffff` in `6lbr` instead of the `RFC6052`?

**Comment by saulofr** [comment]
it is showing in the mapping. I'm using the mosca broquer , could this be?

![image](https://cloud.githubusercontent.com/assets/8770611/15763660/bd3097c8-28fb-11e6-91d9-ad97baf6e423.png)

**Comment by saulofr** [comment]
@alignan, yes I try it, but not work, thanks

**Comment by g-oikonomou** [comment]
Off-topic, but if the thing in the top-left is PuTTY, you should set "Implicit CR every LF" in this session's options (or was it "Implicit LF every CR"???)

**Comment by saulofr** [comment]
CR in every LF, thanks!
