### ISSUE TITLE
LAUNCHXL-CC2650 wrong gpio read

### ISSUE THREAD

**Issue by leojrfs** [contiki-os/contiki#1775]
`ti_lib_gpio_pin_read()` returns 4 or 20, and it varies with the DIO used.

it works fine, returning 0 or 1 using `ti_lib_gpio_read_dio()` from the [latest TI CC13xxware/CC26xxware update](https://github.com/contiki-os/contiki/pull/1756) pull request

**Comment by g-oikonomou** [comment]
From the discussion in #1756, it appears that the reason I closed this one is not clear.

The reason is: The issue reported here is not an issue, it's just how the API works. CCxxware's `GPIOPinRead()` reads multiple pins in one go and returns the combined value of all read pins.

For more details [see its documentation](https://github.com/g-oikonomou/cc26xxware/blob/0270b50ac750f8f3348a98f900a470e7a65ffce8/driverlib/gpio.h#L255).
