### ISSUE TITLE
Possibly unterminated strings in resolv.c

### ISSUE THREAD

**Issue by tonnenpinguin** [contiki-os/contiki#2185]
My static code analysis tool shows several possibly unterminated string warnings for resolv.c, due to the use of [strncpy ](http://www.cplusplus.com/reference/cstring/strncpy/)- which does not implicitly add a null terminator if the original string is longer than len.

This issue occurs in lines [1092](https://github.com/contiki-os/contiki/blob/master/core/net/ip/resolv.c#L1092) and [1252](https://github.com/contiki-os/contiki/blob/master/core/net/ip/resolv.c#L1252), the latter of which causes several other functions to have possibly undefined  behaviour.

~~A relatively easy fix would be to switch to BSD's [strlcpy](http://man.openbsd.org/strlcpy), however, I'm not sure if this is available for all platforms.~~
Enforcing string termination using `resolv_hostname[sizeof(resolv_hostname) - 1] = '\0';` should work.

**Comment by greg-king5** [comment]
Strictly speaking, it isn't a bug because those buffers are one character bigger than the defined limit.  And, they are stored statically.  Therefore, the last byte in those buffers already is `'\0'`.  The `strncpy()` calls don't change it.

The actual bug is in some of the `strncat()` calls.  They assume that the length parameter describes the target buffer -- but, it actually is the maximum number of characters to copy; it doesn't count what already is in the target buffer.  Therefore, those calls can overflow those targets!

**Comment by tonnenpinguin** [comment]
You're right. I've changed my pr to handle the cases you described!
