### ISSUE TITLE
Someone destroyed the Wiki

### ISSUE THREAD

**Issue by nicolashimmelmann** [contiki-os/contiki#2612]
Hi,

I just visited the Wiki and it seems like the user "appleiinc" has overwritten all the pages in there with some acronyms and random letters.

I reverted those changes on all pages possible, however for some pages there was no earlier revision to revert to:

https://github.com/contiki-os/contiki/wiki/8051-Code-Banking
https://github.com/contiki-os/contiki/wiki/8051-Install-and-Use
https://github.com/contiki-os/contiki/wiki/8051-Memory-Spaces
https://github.com/contiki-os/contiki/wiki/The-Arduino-family

Cheers,
Nicolas

**Comment by skrambol** [comment]
Hi,

It was once again deleted and there is no way of reverting them, I think.
![image](https://user-images.githubusercontent.com/13790672/64219135-c5f5ae80-cef6-11e9-82e1-a2eb0a589315.png) The person involved also opened an [issue](https://github.com/contiki-os/contiki/issues/2613).

Back to the problem at hand, are there any more ways to revert the Wiki? Or maybe even have a look or a copy of it? The waybackmachine (e.g. for [the arduino family](https://web.archive.org/web/20170716200716/https://github.com/contiki-os/contiki/wiki/The-Arduino-family)) might help but are there any other ways?

**Comment by dlech** [comment]
Someone with admin access to this repo would be able to reset and force push the wiki via git.

https://help.github.com/en/articles/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer

**Comment by leosteinfeld** [comment]
I could get a particular page thanks to the google cache ("An introduction to Cooja",  we refer to it for an undergraduate course). Despite of contiki-ng, it would be nice to keep wiki pages and the repo as references.
Best
Leo S.

El 3 de septiembre de 2019 10:34:51 p. m. GMT-03:00, Christopher Templado <notifications@github.com> escribió:
>Hi,
>
>It was once again deleted and there is no way of reverting them, I
>think.
>![image](https://user-images.githubusercontent.com/13790672/64219135-c5f5ae80-cef6-11e9-82e1-a2eb0a589315.png)
>The person involved also opened an
>[issue](https://github.com/contiki-os/contiki/issues/2613).
>
>Back to the problem at hand, are there any more ways to revert the
>Wiki? Or maybe even have a look or a copy of it? The waybackmachine
>(e.g. for [the arduino
>family](https://web.archive.org/web/20170716200716/https://github.com/contiki-os/contiki/wiki/The-Arduino-family))
>might help but are there any other ways?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/contiki-os/contiki/issues/2612#issuecomment-527702661

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by oliverschmidt** [comment]
Hi,

Given the current overall situation (number of Wiki contributions in the recent past, existence of contiki-ng) it seems reasonable to make the Wiki R/O for the public - which prevents things like we experienced now. It turns out that I have the right to do so - so I did it:

![image](https://user-images.githubusercontent.com/2664009/64248788-686f5b00-cf12-11e9-906c-6dc006dece8f.png)

Hoping "everybody" agrees with that approach the next question is how to restore the Wiki again - and this time for good. I personally don't know how - and to be honest I don't have the time budget to investigate how to do it.

However, in case it turns out that I have the right to give somebody the necessary access rights who is willing and able to do it please follow up here and I'll provide the access rights.

If it turns out that I don't have the right to give the necessary access rights, I'm willing to reach out to someone who has and ask him to provide the rights.

Oliver

**Comment by dfangl** [comment]
As dlech mentioned, there is a repository for the wiki changes, which you can revert, I already tested that.

The most recent commit, before any changes (as far as I could tell) was 8a707cdc8 (in the wiki).

You can clone it by cloning `git@github.com:contiki-os/contiki.wiki.git`

Revert it with `git revert --no-commit 8a707cdc8..HEAD`

And then commit it again. Using this, no history is destroyed (even if the history ist just deleting files). 
You should also be able to push it afterwards, I sadly do not have the permission for that. (and I actually do not know which permissions you would need for pushing to the wiki directly)

**Comment by bthebaudeau** [comment]
I've just reverted the offending commit range.
