### ISSUE TITLE
java bug

### ISSUE THREAD

**Issue by codeguru1** [contiki-os/contiki#564]
I get this error, if I try to simulate any examples(for eg broadcast) with cooja mote:

     [java] java.lang.ArrayIndexOutOfBoundsException: -339799724
     [java] 	at java.util.ArrayList$Itr.next(ArrayList.java:839)
     [java] 	at se.sics.cooja.SectionMoteMemory.getMemorySegment(SectionMoteMemory.java:94)
     [java] 	at se.sics.cooja.SectionMoteMemory$PolledMemorySegments.notifyIfChanged(SectionMoteMemory.java:394)
     [java] 	at se.sics.cooja.SectionMoteMemory$PolledMemorySegments.access$000(SectionMoteMemory.java:379)
     [java] 	at se.sics.cooja.SectionMoteMemory.pollForMemoryChanges(SectionMoteMemory.java:375)
     [java] 	at se.sics.cooja.contikimote.ContikiMote.execute(ContikiMote.java:147)
     [java] 	at se.sics.cooja.motes.AbstractWakeupMote$1.execute(AbstractWakeupMote.java:47)
     [java] 	at se.sics.cooja.Simulation.run(Simulation.java:280)
     [java] 	at java.lang.Thread.run(Thread.java:744)

**Comment by grbsn** [comment]
@mNisblee thanks!

**Comment by vishal623** [comment]
Hello,
I get this error when I run the Nomadic mobility model in Cooja. I use rpl-collect example for create sink and sender. Then apply my nomadic movement file to my simulation. After 10:00:000 it give me this error.

java.lang.RuntimeException: Next event is in the past: 124522487 < 606641503: Mobility$2@18db030
     [java] 	at se.sics.cooja.Simulation.run(Simulation.java:276)
     [java] 	at java.lang.Thread.run(Thread.java:745)

This error because of simulation time or other? I generate nomadic movements for 600 sec using bonnmotion.

Please help me.
