### ISSUE TITLE
Some questions about ContikiMAC for CC2530

### ISSUE THREAD

**Issue by senspace** [contiki-os/contiki#785]
I have some questions about the ContikiMAC power-saving radio duty cycling protocol. 
For the platform of cc2530, the contikimac just turns the radio on or off. The MCU doesn't enter the PM1 or PM2. So the  power consumption is still very high.
    
/*******************************part of the code*************************/
file: contikimac.c

/* MCU can sleep during radio off */
#ifndef RDC_CONF_MCU_SLEEP
#define RDC_CONF_MCU_SLEEP           0
#endif

      /* Schedule the next powercycle interrupt, or sleep the mcu
	 until then.  Sleeping will not exit from this interrupt, so
	 ensure an occasional wake cycle or foreground processing will
	 be blocked until a packet is detected */
#if RDC_CONF_MCU_SLEEP
      static uint8_t sleepcycle;
      if((sleepcycle++ < 16) && !we_are_sending && !radio_is_on) {
        rtimer_arch_sleep(CYCLE_TIME - (RTIMER_NOW() - cycle_start));
      } else {
        sleepcycle = 0;
        schedule_powercycle_fixed(t, CYCLE_TIME + cycle_start);
        PT_YIELD(&pt);
      }
#else
      ....
/*******************************part of the code*************************/

When "#define RDC_CONF_MCU_SLEEP    1", the MCU can sleep during radio off. But  For the platform of cc2530, the function "rtimer_arch_sleep(CYCLE_TIME - (RTIMER_NOW() - cycle_start));" is not defined. So The MCU doesn't enter the PM1 or PM2.
        For the platform of cc2530, the contikimac just turns the radio on or off. The MCU doesn't enter the PM1 or PM2. So the  power consumption is still very high. Can you give me some advices?

**Comment by tungnguyens** [comment]
Hi, G-Oikonomou

I'm a student at Vietnam university. I'm interested in Contiki Sensinode, thank to it, I can load UDP code to cc2530 with Nullrdc.

But when I define ContikiMac in order to save energy for my project in school, It has reboot.

I saw your reply in below message in 2012 that ContikiMac is not released though It had fixed.
https://sourceforge.net/p/contiki/mailman/message/30007720/

I wonder whether It has released now, Thanks for your support. Cant wait to see your reply.

Nguyen Son Tung.
